---
- name: Set cron vars for {{ job.key }}
  include_tasks: db/cron_vars.yml
- name: Create cron jobs for {{ job.key }}
  cron:
    name: "{{ item.file }}"
    month: "*"
    weekday: "*"
    day: "*"
    hour: "5,2"
    minute: "0"
    job: "PGOPTIONS=--search_path={{ item.schema | default('public') }} psql -f {{ item.file }} > /dev/null"
    state: present
    user: "{{ database_migrations_system_user }}"
    cron_file: "{{ job.key }}"
  with_items: "{{ job.value }}"
  loop_control:
    loop_var: item