---
- name: Run migration
  command: sqitch --registry {{ item.registry }} deploy -t db:{{ item.engine }}://{{ database_migrations_db_connections[plan.key].user }}@{{ database_migrations_db_connections[plan.key].host }}:{{ database_migrations_db_connections[plan.key].port }}/{{ database_migrations_db_connections[plan.key].database }} {{ item.extra_args }}  # noqa 301 204
  args:
    chdir: "{{ item.directory }}"
  become: true
  become_user: "{{ database_migrations_system_user }}"
  with_items: "{{ plan.value }}"
  loop_control:
    loop_var: item
  register: sqitch_output
  failed_when:
    - sqitch_output.rc != 0
