---
- name: Customize logrotate rules
  template:
    src: etc/logrotate.d/sqitch_migrations.j2
    dest: "/etc/logrotate.d/{{ sqitch_migrations_sys_name }}"
    owner: root
    group: root
    mode: 0644
