---
- name: Create SQL cron jobs
  include_tasks: db/cron.yml
  loop: '{{ sqitch_migrations_sql_jobs | dict2items }}'
  loop_control:
    loop_var: job
  when:
    - sqitch_migrations_db_connections.values() | length > 0
    - sqitch_migrations_sql_jobs.values() | length > 0
