---
- name: Run sqitch migrations
  include_tasks: db/sqitch.yml
  loop: '{{ sqitch_migrations_sqitch_plans | dict2items }}'
  loop_control:
    loop_var: plan
  when:
    - sqitch_migrations_db_connections.values() | length > 0
    - sqitch_migrations_sqitch_plans.values() | length > 0
