---
- name: Verify
  hosts: all
  tasks:
    - name: Verify sqitch migrations
      shell: find . -iname sqitch.conf -print0 | sort -zn | xargs -I {} -0 bash -c 'cd `dirname {}` && pwd && sqitch --registry sqitch_test deploy -t db:pg://regular@localhost/productiondb --verify --set schema=test'  # noqa 301
      register: sqitch_result
      args:
        chdir: /home/nomad/reveal
      become: true
      become_user: nomad
    - name: Verify return code
      assert:
        that: sqitch_result.rc == 0
    - name: Check content of pgpass file
      replace:
        path: /home/nomad/pgpass
        regexp: |
          localhost:5432:productiondb:admin:hunter2
          localhost:5432:productiondb:regular:hunter2
      check_mode: true
      register: pgpass_exists
      failed_when: pgpass_exists is changed
    - name: Check content of cron file
      replace:
        path: /etc/cron.d/db_user
        regexp: |
          PGPORT=5432
          PGHOST=localhost
          PGDATABASE=productiondb
          PGUSER=regular
          #Ansible: /home/nomad/reveal/3-reveal/jobs/materialized-views/refresh_jurisdictions_materialized_view.sql
          * * * * * nomad PGOPTIONS=--search_path=test psql -f /home/nomad/reveal/3-reveal/jobs/materialized-views/refresh_jurisdictions_materialized_view.sql >> /var/log/database_migrations/db_user.log 2>&1
          #Ansible: /home/nomad/reveal/3-reveal/jobs/materialized-views/refresh_plans_materialzied_view.sql
          0 */2 * * * nomad PGOPTIONS=--search_path=test psql -f /home/nomad/reveal/3-reveal/jobs/materialized-views/refresh_plans_materialzied_view.sql >> /var/log/database_migrations/db_user.log 2>&1
          #Ansible: /home/nomad/reveal/3-reveal/jobs/materialized-views/refresh_reporting_lag.sql
          * * * 1 * nomad PGOPTIONS=--search_path=test psql -f /home/nomad/reveal/3-reveal/jobs/materialized-views/refresh_reporting_lag.sql >> /var/log/database_migrations/db_user.log 2>&1
          #Ansible: /home/nomad/reveal/3-reveal/jobs/materialized-views/refresh_reporting_time.sql
          * * * * 0 nomad PGOPTIONS=--search_path=test psql -f /home/nomad/reveal/3-reveal/jobs/materialized-views/refresh_reporting_time.sql >> /var/log/database_migrations/db_user.log 2>&1
      check_mode: true
      register: cron_exists
      failed_when: cron_exists is changed
